import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-md": ["Inter"],
        display: ["Geist"],
        "label-md": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg": ["Geist"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Geist"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      spacing: {
        gutter: "24px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        "2xl": "64px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
      },
      colors: {
        outline: "#7b7487",
        "surface-container": "#eaedff",
        "on-tertiary-container": "#ffdedf",
        "on-secondary-fixed-variant": "#004e5c",
        tertiary: "#a0002f",
        "surface-container-high": "#e2e7ff",
        "on-secondary-container": "#006172",
        "on-primary-container": "#ede0ff",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-variant": "#dae2fd",
        "on-background": "#131b2e",
        "on-surface-variant": "#4a4455",
        "primary-fixed-dim": "#d2bbff",
        "tertiary-fixed": "#ffdadb",
        "primary-fixed": "#eaddff",
        "on-secondary-fixed": "#001f26",
        "on-tertiary-fixed-variant": "#92002a",
        "secondary-container": "#57dffe",
        "surface-container-highest": "#dae2fd",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-primary": "#d2bbff",
        "tertiary-fixed-dim": "#ffb2b7",
        "secondary-fixed": "#acedff",
        "secondary": "#00687a",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#7c3aed",
        "surface-dim": "#d2d9f4",
        "inverse-on-surface": "#eef0ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#5a00c6",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f3ff",
        background: "#faf8ff",
        "on-tertiary-fixed": "#40000d",
        "tertiary-container": "#c81a42",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "inverse-surface": "#283044",
        "on-primary": "#ffffff",
        "surface-bright": "#faf8ff",
        surface: "#faf8ff",
        "on-primary-fixed": "#25005a",
        "on-surface": "#131b2e",
        "surface-tint": "#732ee4",
        "outline-variant": "#ccc3d8",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#630ed4",
          foreground: "#ffffff",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        'glass': '0 4px 30px rgba(0, 0, 0, 0.1)',
        'soft': '0 10px 40px -10px rgba(0,0,0,0.08)',
        'glow': 'var(--shadow-glow)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        }
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'hero-gradient': 'var(--gradient-hero)',
      }
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
